// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	dto "fratelli-feccia/internal/dto"
	export "fratelli-feccia/internal/services/export"
	orders "fratelli-feccia/internal/services/orders"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockAdminService is a mock of AdminService interface.
type MockAdminService struct {
	ctrl     *gomock.Controller
	recorder *MockAdminServiceMockRecorder
}

// MockAdminServiceMockRecorder is the mock recorder for MockAdminService.
type MockAdminServiceMockRecorder struct {
	mock *MockAdminService
}

// NewMockAdminService creates a new mock instance.
func NewMockAdminService(ctrl *gomock.Controller) *MockAdminService {
	mock := &MockAdminService{ctrl: ctrl}
	mock.recorder = &MockAdminServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminService) EXPECT() *MockAdminServiceMockRecorder {
	return m.recorder
}

// CountAdmins mocks base method.
func (m *MockAdminService) CountAdmins(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountAdmins", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountAdmins indicates an expected call of CountAdmins.
func (mr *MockAdminServiceMockRecorder) CountAdmins(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountAdmins", reflect.TypeOf((*MockAdminService)(nil).CountAdmins), ctx)
}

// CreateUser mocks base method.
func (m *MockAdminService) CreateUser(ctx context.Context, req dto.CreateUserRequest) (*dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, req)
	ret0, _ := ret[0].(*dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAdminServiceMockRecorder) CreateUser(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAdminService)(nil).CreateUser), ctx, req)
}

// DeleteUser mocks base method.
func (m *MockAdminService) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockAdminServiceMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockAdminService)(nil).DeleteUser), ctx, id)
}

// GetUserByID mocks base method.
func (m *MockAdminService) GetUserByID(ctx context.Context, id int64) (*dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockAdminServiceMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockAdminService)(nil).GetUserByID), ctx, id)
}

// ListAllUsers mocks base method.
func (m *MockAdminService) ListAllUsers(ctx context.Context) ([]dto.AuthUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllUsers", ctx)
	ret0, _ := ret[0].([]dto.AuthUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllUsers indicates an expected call of ListAllUsers.
func (mr *MockAdminServiceMockRecorder) ListAllUsers(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllUsers", reflect.TypeOf((*MockAdminService)(nil).ListAllUsers), ctx)
}

// ListUsers mocks base method.
func (m *MockAdminService) ListUsers(ctx context.Context, page, limit int) ([]dto.UserResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, page, limit)
	ret0, _ := ret[0].([]dto.UserResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockAdminServiceMockRecorder) ListUsers(ctx, page, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockAdminService)(nil).ListUsers), ctx, page, limit)
}

// PatchUser mocks base method.
func (m *MockAdminService) PatchUser(ctx context.Context, id int64, req dto.PatchUserRequest) (*dto.AuthUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchUser", ctx, id, req)
	ret0, _ := ret[0].(*dto.AuthUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchUser indicates an expected call of PatchUser.
func (mr *MockAdminServiceMockRecorder) PatchUser(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchUser", reflect.TypeOf((*MockAdminService)(nil).PatchUser), ctx, id, req)
}

// UpdateUser mocks base method.
func (m *MockAdminService) UpdateUser(ctx context.Context, id int64, item dto.UpdateUserRequest) (*dto.UserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, item)
	ret0, _ := ret[0].(*dto.UserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAdminServiceMockRecorder) UpdateUser(ctx, id, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAdminService)(nil).UpdateUser), ctx, id, item)
}

// MockAuth is a mock of Auth interface.
type MockAuth struct {
	ctrl     *gomock.Controller
	recorder *MockAuthMockRecorder
}

// MockAuthMockRecorder is the mock recorder for MockAuth.
type MockAuthMockRecorder struct {
	mock *MockAuth
}

// NewMockAuth creates a new mock instance.
func NewMockAuth(ctrl *gomock.Controller) *MockAuth {
	mock := &MockAuth{ctrl: ctrl}
	mock.recorder = &MockAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuth) EXPECT() *MockAuthMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuth) Login(login, password string) (*dto.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", login, password)
	ret0, _ := ret[0].(*dto.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthMockRecorder) Login(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuth)(nil).Login), login, password)
}

// Me mocks base method.
func (m *MockAuth) Me(userID int64) (*dto.AuthUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Me", userID)
	ret0, _ := ret[0].(*dto.AuthUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Me indicates an expected call of Me.
func (mr *MockAuthMockRecorder) Me(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Me", reflect.TypeOf((*MockAuth)(nil).Me), userID)
}

// Refresh mocks base method.
func (m *MockAuth) Refresh(refreshToken string) (*dto.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", refreshToken)
	ret0, _ := ret[0].(*dto.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockAuthMockRecorder) Refresh(refreshToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockAuth)(nil).Refresh), refreshToken)
}

// Register mocks base method.
func (m *MockAuth) Register(req dto.RegisterRequest) (*dto.AuthUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", req)
	ret0, _ := ret[0].(*dto.AuthUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthMockRecorder) Register(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuth)(nil).Register), req)
}

// RegisterClient mocks base method.
func (m *MockAuth) RegisterClient(req dto.ClientRegisterRequest) (*dto.LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterClient", req)
	ret0, _ := ret[0].(*dto.LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterClient indicates an expected call of RegisterClient.
func (mr *MockAuthMockRecorder) RegisterClient(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterClient", reflect.TypeOf((*MockAuth)(nil).RegisterClient), req)
}

// MockCustomer is a mock of Customer interface.
type MockCustomer struct {
	ctrl     *gomock.Controller
	recorder *MockCustomerMockRecorder
}

// MockCustomerMockRecorder is the mock recorder for MockCustomer.
type MockCustomerMockRecorder struct {
	mock *MockCustomer
}

// NewMockCustomer creates a new mock instance.
func NewMockCustomer(ctrl *gomock.Controller) *MockCustomer {
	mock := &MockCustomer{ctrl: ctrl}
	mock.recorder = &MockCustomerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomer) EXPECT() *MockCustomerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomer) Create(ctx context.Context, req dto.CustomerRequest) (*dto.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomerMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomer)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockCustomer) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCustomerMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCustomer)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCustomer) GetByID(ctx context.Context, id uuid.UUID) (*dto.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCustomerMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCustomer)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCustomer) List(ctx context.Context, search string) ([]dto.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, search)
	ret0, _ := ret[0].([]dto.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCustomerMockRecorder) List(ctx, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCustomer)(nil).List), ctx, search)
}

// Update mocks base method.
func (m *MockCustomer) Update(ctx context.Context, id uuid.UUID, req dto.CustomerRequest) (*dto.CustomerResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.CustomerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCustomerMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCustomer)(nil).Update), ctx, id, req)
}

// MockDestination is a mock of Destination interface.
type MockDestination struct {
	ctrl     *gomock.Controller
	recorder *MockDestinationMockRecorder
}

// MockDestinationMockRecorder is the mock recorder for MockDestination.
type MockDestinationMockRecorder struct {
	mock *MockDestination
}

// NewMockDestination creates a new mock instance.
func NewMockDestination(ctrl *gomock.Controller) *MockDestination {
	mock := &MockDestination{ctrl: ctrl}
	mock.recorder = &MockDestinationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDestination) EXPECT() *MockDestinationMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDestination) Create(ctx context.Context, req dto.DestinationRequest) (*dto.DestinationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.DestinationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDestinationMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDestination)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockDestination) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDestinationMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDestination)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockDestination) GetByID(ctx context.Context, id uuid.UUID) (*dto.DestinationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.DestinationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDestinationMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDestination)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockDestination) List(ctx context.Context, search string, includeInactive bool) ([]dto.DestinationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, search, includeInactive)
	ret0, _ := ret[0].([]dto.DestinationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDestinationMockRecorder) List(ctx, search, includeInactive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDestination)(nil).List), ctx, search, includeInactive)
}

// Update mocks base method.
func (m *MockDestination) Update(ctx context.Context, id uuid.UUID, req dto.DestinationRequest) (*dto.DestinationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.DestinationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDestinationMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDestination)(nil).Update), ctx, id, req)
}

// MockCarrier is a mock of Carrier interface.
type MockCarrier struct {
	ctrl     *gomock.Controller
	recorder *MockCarrierMockRecorder
}

// MockCarrierMockRecorder is the mock recorder for MockCarrier.
type MockCarrierMockRecorder struct {
	mock *MockCarrier
}

// NewMockCarrier creates a new mock instance.
func NewMockCarrier(ctrl *gomock.Controller) *MockCarrier {
	mock := &MockCarrier{ctrl: ctrl}
	mock.recorder = &MockCarrierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCarrier) EXPECT() *MockCarrierMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCarrier) Create(ctx context.Context, req dto.CarrierRequest) (*dto.CarrierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.CarrierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCarrierMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCarrier)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockCarrier) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCarrierMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCarrier)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockCarrier) List(ctx context.Context, search string) ([]dto.CarrierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, search)
	ret0, _ := ret[0].([]dto.CarrierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCarrierMockRecorder) List(ctx, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCarrier)(nil).List), ctx, search)
}

// Update mocks base method.
func (m *MockCarrier) Update(ctx context.Context, id uuid.UUID, req dto.CarrierRequest) (*dto.CarrierResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.CarrierResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCarrierMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCarrier)(nil).Update), ctx, id, req)
}

// MockGarage is a mock of Garage interface.
type MockGarage struct {
	ctrl     *gomock.Controller
	recorder *MockGarageMockRecorder
}

// MockGarageMockRecorder is the mock recorder for MockGarage.
type MockGarageMockRecorder struct {
	mock *MockGarage
}

// NewMockGarage creates a new mock instance.
func NewMockGarage(ctrl *gomock.Controller) *MockGarage {
	mock := &MockGarage{ctrl: ctrl}
	mock.recorder = &MockGarageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGarage) EXPECT() *MockGarageMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGarage) Create(ctx context.Context, req dto.GarageRequest) (*dto.GarageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.GarageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockGarageMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGarage)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockGarage) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGarageMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGarage)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockGarage) List(ctx context.Context, includeInactive bool) ([]dto.GarageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, includeInactive)
	ret0, _ := ret[0].([]dto.GarageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockGarageMockRecorder) List(ctx, includeInactive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockGarage)(nil).List), ctx, includeInactive)
}

// Update mocks base method.
func (m *MockGarage) Update(ctx context.Context, id uuid.UUID, req dto.GarageRequest) (*dto.GarageResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.GarageResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGarageMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGarage)(nil).Update), ctx, id, req)
}

// MockWashStation is a mock of WashStation interface.
type MockWashStation struct {
	ctrl     *gomock.Controller
	recorder *MockWashStationMockRecorder
}

// MockWashStationMockRecorder is the mock recorder for MockWashStation.
type MockWashStationMockRecorder struct {
	mock *MockWashStation
}

// NewMockWashStation creates a new mock instance.
func NewMockWashStation(ctrl *gomock.Controller) *MockWashStation {
	mock := &MockWashStation{ctrl: ctrl}
	mock.recorder = &MockWashStationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWashStation) EXPECT() *MockWashStationMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWashStation) Create(ctx context.Context, req dto.WashStationRequest) (*dto.WashStationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.WashStationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWashStationMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWashStation)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockWashStation) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWashStationMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWashStation)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockWashStation) List(ctx context.Context, includeInactive bool) ([]dto.WashStationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, includeInactive)
	ret0, _ := ret[0].([]dto.WashStationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWashStationMockRecorder) List(ctx, includeInactive interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWashStation)(nil).List), ctx, includeInactive)
}

// Update mocks base method.
func (m *MockWashStation) Update(ctx context.Context, id uuid.UUID, req dto.WashStationRequest) (*dto.WashStationResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.WashStationResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWashStationMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWashStation)(nil).Update), ctx, id, req)
}

// MockDriver is a mock of Driver interface.
type MockDriver struct {
	ctrl     *gomock.Controller
	recorder *MockDriverMockRecorder
}

// MockDriverMockRecorder is the mock recorder for MockDriver.
type MockDriverMockRecorder struct {
	mock *MockDriver
}

// NewMockDriver creates a new mock instance.
func NewMockDriver(ctrl *gomock.Controller) *MockDriver {
	mock := &MockDriver{ctrl: ctrl}
	mock.recorder = &MockDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriver) EXPECT() *MockDriverMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDriver) Create(ctx context.Context, req dto.DriverRequest) (*dto.DriverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.DriverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDriverMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDriver)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockDriver) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDriverMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDriver)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockDriver) List(ctx context.Context, search string) ([]dto.DriverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, search)
	ret0, _ := ret[0].([]dto.DriverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDriverMockRecorder) List(ctx, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDriver)(nil).List), ctx, search)
}

// Update mocks base method.
func (m *MockDriver) Update(ctx context.Context, id uuid.UUID, req dto.DriverRequest) (*dto.DriverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.DriverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDriverMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDriver)(nil).Update), ctx, id, req)
}

// MockProduct is a mock of Product interface.
type MockProduct struct {
	ctrl     *gomock.Controller
	recorder *MockProductMockRecorder
}

// MockProductMockRecorder is the mock recorder for MockProduct.
type MockProductMockRecorder struct {
	mock *MockProduct
}

// NewMockProduct creates a new mock instance.
func NewMockProduct(ctrl *gomock.Controller) *MockProduct {
	mock := &MockProduct{ctrl: ctrl}
	mock.recorder = &MockProductMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProduct) EXPECT() *MockProductMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProduct) Create(ctx context.Context, req dto.ProductRequest) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProductMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProduct)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockProduct) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProductMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProduct)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockProduct) List(ctx context.Context, search string) ([]dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, search)
	ret0, _ := ret[0].([]dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProductMockRecorder) List(ctx, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProduct)(nil).List), ctx, search)
}

// Update mocks base method.
func (m *MockProduct) Update(ctx context.Context, id uuid.UUID, req dto.ProductRequest) (*dto.ProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.ProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProductMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProduct)(nil).Update), ctx, id, req)
}

// MockMasterdata is a mock of Masterdata interface.
type MockMasterdata struct {
	ctrl     *gomock.Controller
	recorder *MockMasterdataMockRecorder
}

// MockMasterdataMockRecorder is the mock recorder for MockMasterdata.
type MockMasterdataMockRecorder struct {
	mock *MockMasterdata
}

// NewMockMasterdata creates a new mock instance.
func NewMockMasterdata(ctrl *gomock.Controller) *MockMasterdata {
	mock := &MockMasterdata{ctrl: ctrl}
	mock.recorder = &MockMasterdataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMasterdata) EXPECT() *MockMasterdataMockRecorder {
	return m.recorder
}

// CreateAccessoryCost mocks base method.
func (m *MockMasterdata) CreateAccessoryCost(ctx context.Context, req dto.AccessoryCostRequest) (*dto.AccessoryCostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessoryCost", ctx, req)
	ret0, _ := ret[0].(*dto.AccessoryCostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccessoryCost indicates an expected call of CreateAccessoryCost.
func (mr *MockMasterdataMockRecorder) CreateAccessoryCost(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessoryCost", reflect.TypeOf((*MockMasterdata)(nil).CreateAccessoryCost), ctx, req)
}

// CreateTransportCategory mocks base method.
func (m *MockMasterdata) CreateTransportCategory(ctx context.Context, req dto.TransportCategoryRequest) (*dto.TransportCategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransportCategory", ctx, req)
	ret0, _ := ret[0].(*dto.TransportCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransportCategory indicates an expected call of CreateTransportCategory.
func (mr *MockMasterdataMockRecorder) CreateTransportCategory(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransportCategory", reflect.TypeOf((*MockMasterdata)(nil).CreateTransportCategory), ctx, req)
}

// CreateVehicleType mocks base method.
func (m *MockMasterdata) CreateVehicleType(ctx context.Context, req dto.VehicleTypeRequest) (*dto.VehicleTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVehicleType", ctx, req)
	ret0, _ := ret[0].(*dto.VehicleTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVehicleType indicates an expected call of CreateVehicleType.
func (mr *MockMasterdataMockRecorder) CreateVehicleType(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVehicleType", reflect.TypeOf((*MockMasterdata)(nil).CreateVehicleType), ctx, req)
}

// ListAccessoryCosts mocks base method.
func (m *MockMasterdata) ListAccessoryCosts(ctx context.Context) ([]dto.AccessoryCostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccessoryCosts", ctx)
	ret0, _ := ret[0].([]dto.AccessoryCostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccessoryCosts indicates an expected call of ListAccessoryCosts.
func (mr *MockMasterdataMockRecorder) ListAccessoryCosts(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccessoryCosts", reflect.TypeOf((*MockMasterdata)(nil).ListAccessoryCosts), ctx)
}

// ListTransportCategories mocks base method.
func (m *MockMasterdata) ListTransportCategories(ctx context.Context) ([]dto.TransportCategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransportCategories", ctx)
	ret0, _ := ret[0].([]dto.TransportCategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransportCategories indicates an expected call of ListTransportCategories.
func (mr *MockMasterdataMockRecorder) ListTransportCategories(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransportCategories", reflect.TypeOf((*MockMasterdata)(nil).ListTransportCategories), ctx)
}

// ListVehicleTypes mocks base method.
func (m *MockMasterdata) ListVehicleTypes(ctx context.Context) ([]dto.VehicleTypeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVehicleTypes", ctx)
	ret0, _ := ret[0].([]dto.VehicleTypeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVehicleTypes indicates an expected call of ListVehicleTypes.
func (mr *MockMasterdataMockRecorder) ListVehicleTypes(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVehicleTypes", reflect.TypeOf((*MockMasterdata)(nil).ListVehicleTypes), ctx)
}

// MockAnagrafiche is a mock of Anagrafiche interface.
type MockAnagrafiche struct {
	ctrl     *gomock.Controller
	recorder *MockAnagraficheMockRecorder
}

// MockAnagraficheMockRecorder is the mock recorder for MockAnagrafiche.
type MockAnagraficheMockRecorder struct {
	mock *MockAnagrafiche
}

// NewMockAnagrafiche creates a new mock instance.
func NewMockAnagrafiche(ctrl *gomock.Controller) *MockAnagrafiche {
	mock := &MockAnagrafiche{ctrl: ctrl}
	mock.recorder = &MockAnagraficheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnagrafiche) EXPECT() *MockAnagraficheMockRecorder {
	return m.recorder
}

// CreateAccountingEntry mocks base method.
func (m *MockAnagrafiche) CreateAccountingEntry(ctx context.Context, req dto.AccountingEntryRequest) (*dto.AccountingEntryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccountingEntry", ctx, req)
	ret0, _ := ret[0].(*dto.AccountingEntryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAccountingEntry indicates an expected call of CreateAccountingEntry.
func (mr *MockAnagraficheMockRecorder) CreateAccountingEntry(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccountingEntry", reflect.TypeOf((*MockAnagrafiche)(nil).CreateAccountingEntry), ctx, req)
}

// CreateBank mocks base method.
func (m *MockAnagrafiche) CreateBank(ctx context.Context, req dto.BankRequest) (*dto.BankResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBank", ctx, req)
	ret0, _ := ret[0].(*dto.BankResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBank indicates an expected call of CreateBank.
func (mr *MockAnagraficheMockRecorder) CreateBank(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBank", reflect.TypeOf((*MockAnagrafiche)(nil).CreateBank), ctx, req)
}

// CreateCountry mocks base method.
func (m *MockAnagrafiche) CreateCountry(ctx context.Context, req dto.CountryRequest) (*dto.CountryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCountry", ctx, req)
	ret0, _ := ret[0].(*dto.CountryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCountry indicates an expected call of CreateCountry.
func (mr *MockAnagraficheMockRecorder) CreateCountry(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCountry", reflect.TypeOf((*MockAnagrafiche)(nil).CreateCountry), ctx, req)
}

// DeleteAccountingEntry mocks base method.
func (m *MockAnagrafiche) DeleteAccountingEntry(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccountingEntry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccountingEntry indicates an expected call of DeleteAccountingEntry.
func (mr *MockAnagraficheMockRecorder) DeleteAccountingEntry(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccountingEntry", reflect.TypeOf((*MockAnagrafiche)(nil).DeleteAccountingEntry), ctx, id)
}

// DeleteBank mocks base method.
func (m *MockAnagrafiche) DeleteBank(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBank", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBank indicates an expected call of DeleteBank.
func (mr *MockAnagraficheMockRecorder) DeleteBank(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBank", reflect.TypeOf((*MockAnagrafiche)(nil).DeleteBank), ctx, id)
}

// DeleteCountry mocks base method.
func (m *MockAnagrafiche) DeleteCountry(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCountry", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCountry indicates an expected call of DeleteCountry.
func (mr *MockAnagraficheMockRecorder) DeleteCountry(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCountry", reflect.TypeOf((*MockAnagrafiche)(nil).DeleteCountry), ctx, id)
}

// ListAccountingEntries mocks base method.
func (m *MockAnagrafiche) ListAccountingEntries(ctx context.Context, search, tipo string) ([]dto.AccountingEntryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountingEntries", ctx, search, tipo)
	ret0, _ := ret[0].([]dto.AccountingEntryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountingEntries indicates an expected call of ListAccountingEntries.
func (mr *MockAnagraficheMockRecorder) ListAccountingEntries(ctx, search, tipo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountingEntries", reflect.TypeOf((*MockAnagrafiche)(nil).ListAccountingEntries), ctx, search, tipo)
}

// ListBanks mocks base method.
func (m *MockAnagrafiche) ListBanks(ctx context.Context, search string) ([]dto.BankResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBanks", ctx, search)
	ret0, _ := ret[0].([]dto.BankResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBanks indicates an expected call of ListBanks.
func (mr *MockAnagraficheMockRecorder) ListBanks(ctx, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBanks", reflect.TypeOf((*MockAnagrafiche)(nil).ListBanks), ctx, search)
}

// ListCountries mocks base method.
func (m *MockAnagrafiche) ListCountries(ctx context.Context, search string) ([]dto.CountryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCountries", ctx, search)
	ret0, _ := ret[0].([]dto.CountryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCountries indicates an expected call of ListCountries.
func (mr *MockAnagraficheMockRecorder) ListCountries(ctx, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCountries", reflect.TypeOf((*MockAnagrafiche)(nil).ListCountries), ctx, search)
}

// UpdateAccountingEntry mocks base method.
func (m *MockAnagrafiche) UpdateAccountingEntry(ctx context.Context, id uuid.UUID, req dto.AccountingEntryRequest) (*dto.AccountingEntryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountingEntry", ctx, id, req)
	ret0, _ := ret[0].(*dto.AccountingEntryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAccountingEntry indicates an expected call of UpdateAccountingEntry.
func (mr *MockAnagraficheMockRecorder) UpdateAccountingEntry(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountingEntry", reflect.TypeOf((*MockAnagrafiche)(nil).UpdateAccountingEntry), ctx, id, req)
}

// UpdateBank mocks base method.
func (m *MockAnagrafiche) UpdateBank(ctx context.Context, id uuid.UUID, req dto.BankRequest) (*dto.BankResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBank", ctx, id, req)
	ret0, _ := ret[0].(*dto.BankResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBank indicates an expected call of UpdateBank.
func (mr *MockAnagraficheMockRecorder) UpdateBank(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBank", reflect.TypeOf((*MockAnagrafiche)(nil).UpdateBank), ctx, id, req)
}

// UpdateCountry mocks base method.
func (m *MockAnagrafiche) UpdateCountry(ctx context.Context, id uuid.UUID, req dto.CountryRequest) (*dto.CountryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCountry", ctx, id, req)
	ret0, _ := ret[0].(*dto.CountryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCountry indicates an expected call of UpdateCountry.
func (mr *MockAnagraficheMockRecorder) UpdateCountry(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCountry", reflect.TypeOf((*MockAnagrafiche)(nil).UpdateCountry), ctx, id, req)
}

// MockDriverUnavailability is a mock of DriverUnavailability interface.
type MockDriverUnavailability struct {
	ctrl     *gomock.Controller
	recorder *MockDriverUnavailabilityMockRecorder
}

// MockDriverUnavailabilityMockRecorder is the mock recorder for MockDriverUnavailability.
type MockDriverUnavailabilityMockRecorder struct {
	mock *MockDriverUnavailability
}

// NewMockDriverUnavailability creates a new mock instance.
func NewMockDriverUnavailability(ctrl *gomock.Controller) *MockDriverUnavailability {
	mock := &MockDriverUnavailability{ctrl: ctrl}
	mock.recorder = &MockDriverUnavailabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDriverUnavailability) EXPECT() *MockDriverUnavailabilityMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDriverUnavailability) Create(ctx context.Context, req dto.DriverUnavailabilityRequest) (*dto.DriverUnavailabilityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.DriverUnavailabilityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDriverUnavailabilityMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDriverUnavailability)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockDriverUnavailability) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDriverUnavailabilityMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDriverUnavailability)(nil).Delete), ctx, id)
}

// List mocks base method.
func (m *MockDriverUnavailability) List(ctx context.Context, autistaID uuid.UUID, dataDa, dataA string) ([]dto.DriverUnavailabilityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, autistaID, dataDa, dataA)
	ret0, _ := ret[0].([]dto.DriverUnavailabilityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDriverUnavailabilityMockRecorder) List(ctx, autistaID, dataDa, dataA interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDriverUnavailability)(nil).List), ctx, autistaID, dataDa, dataA)
}

// MockOrder is a mock of Order interface.
type MockOrder struct {
	ctrl     *gomock.Controller
	recorder *MockOrderMockRecorder
}

// MockOrderMockRecorder is the mock recorder for MockOrder.
type MockOrderMockRecorder struct {
	mock *MockOrder
}

// NewMockOrder creates a new mock instance.
func NewMockOrder(ctrl *gomock.Controller) *MockOrder {
	mock := &MockOrder{ctrl: ctrl}
	mock.recorder = &MockOrderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrder) EXPECT() *MockOrderMockRecorder {
	return m.recorder
}

// Assign mocks base method.
func (m *MockOrder) Assign(ctx context.Context, id uuid.UUID, req dto.OrderAssignRequest) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assign", ctx, id, req)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Assign indicates an expected call of Assign.
func (mr *MockOrderMockRecorder) Assign(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assign", reflect.TypeOf((*MockOrder)(nil).Assign), ctx, id, req)
}

// Close mocks base method.
func (m *MockOrder) Close(ctx context.Context, id uuid.UUID) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, id)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Close indicates an expected call of Close.
func (mr *MockOrderMockRecorder) Close(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockOrder)(nil).Close), ctx, id)
}

// Create mocks base method.
func (m *MockOrder) Create(ctx context.Context, req dto.OrderRequest) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockOrderMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrder)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockOrder) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrderMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrder)(nil).Delete), ctx, id)
}

// Discard mocks base method.
func (m *MockOrder) Discard(ctx context.Context, id uuid.UUID) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discard", ctx, id)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Discard indicates an expected call of Discard.
func (mr *MockOrderMockRecorder) Discard(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discard", reflect.TypeOf((*MockOrder)(nil).Discard), ctx, id)
}

// GetByID mocks base method.
func (m *MockOrder) GetByID(ctx context.Context, id uuid.UUID) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrderMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrder)(nil).GetByID), ctx, id)
}

// GetCMRPDF mocks base method.
func (m *MockOrder) GetCMRPDF(ctx context.Context, id uuid.UUID) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCMRPDF", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCMRPDF indicates an expected call of GetCMRPDF.
func (mr *MockOrderMockRecorder) GetCMRPDF(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCMRPDF", reflect.TypeOf((*MockOrder)(nil).GetCMRPDF), ctx, id)
}

// List mocks base method.
func (m *MockOrder) List(ctx context.Context, f orders.ListFilters) ([]dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, f)
	ret0, _ := ret[0].([]dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrderMockRecorder) List(ctx, f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrder)(nil).List), ctx, f)
}

// ReturnSuggestions mocks base method.
func (m *MockOrder) ReturnSuggestions(ctx context.Context, id uuid.UUID, maxDaysGap, limit int) (*dto.OrderReturnSuggestionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReturnSuggestions", ctx, id, maxDaysGap, limit)
	ret0, _ := ret[0].(*dto.OrderReturnSuggestionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReturnSuggestions indicates an expected call of ReturnSuggestions.
func (mr *MockOrderMockRecorder) ReturnSuggestions(ctx, id, maxDaysGap, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReturnSuggestions", reflect.TypeOf((*MockOrder)(nil).ReturnSuggestions), ctx, id, maxDaysGap, limit)
}

// RouteAlternatives mocks base method.
func (m *MockOrder) RouteAlternatives(ctx context.Context, id uuid.UUID, garageID, washStationID string) ([]dto.RouteAlternativeDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RouteAlternatives", ctx, id, garageID, washStationID)
	ret0, _ := ret[0].([]dto.RouteAlternativeDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RouteAlternatives indicates an expected call of RouteAlternatives.
func (mr *MockOrderMockRecorder) RouteAlternatives(ctx, id, garageID, washStationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteAlternatives", reflect.TypeOf((*MockOrder)(nil).RouteAlternatives), ctx, id, garageID, washStationID)
}

// Start mocks base method.
func (m *MockOrder) Start(ctx context.Context, id uuid.UUID) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, id)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockOrderMockRecorder) Start(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockOrder)(nil).Start), ctx, id)
}

// Unassign mocks base method.
func (m *MockOrder) Unassign(ctx context.Context, id uuid.UUID) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unassign", ctx, id)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unassign indicates an expected call of Unassign.
func (mr *MockOrderMockRecorder) Unassign(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unassign", reflect.TypeOf((*MockOrder)(nil).Unassign), ctx, id)
}

// Update mocks base method.
func (m *MockOrder) Update(ctx context.Context, id uuid.UUID, req dto.OrderRequest) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockOrderMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrder)(nil).Update), ctx, id, req)
}

// UpdateRoute mocks base method.
func (m *MockOrder) UpdateRoute(ctx context.Context, id uuid.UUID, waypoints []dto.RouteWaypointDTO) (*dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoute", ctx, id, waypoints)
	ret0, _ := ret[0].(*dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoute indicates an expected call of UpdateRoute.
func (mr *MockOrderMockRecorder) UpdateRoute(ctx, id, waypoints interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoute", reflect.TypeOf((*MockOrder)(nil).UpdateRoute), ctx, id, waypoints)
}

// MockVehicle is a mock of Vehicle interface.
type MockVehicle struct {
	ctrl     *gomock.Controller
	recorder *MockVehicleMockRecorder
}

// MockVehicleMockRecorder is the mock recorder for MockVehicle.
type MockVehicleMockRecorder struct {
	mock *MockVehicle
}

// NewMockVehicle creates a new mock instance.
func NewMockVehicle(ctrl *gomock.Controller) *MockVehicle {
	mock := &MockVehicle{ctrl: ctrl}
	mock.recorder = &MockVehicleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVehicle) EXPECT() *MockVehicleMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVehicle) Create(ctx context.Context, req dto.VehicleRequest) (*dto.VehicleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.VehicleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVehicleMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVehicle)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockVehicle) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVehicleMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVehicle)(nil).Delete), ctx, id)
}

// GetAllGPSLive mocks base method.
func (m *MockVehicle) GetAllGPSLive(ctx context.Context) ([]dto.GPSLiveVehicle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGPSLive", ctx)
	ret0, _ := ret[0].([]dto.GPSLiveVehicle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGPSLive indicates an expected call of GetAllGPSLive.
func (mr *MockVehicleMockRecorder) GetAllGPSLive(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGPSLive", reflect.TypeOf((*MockVehicle)(nil).GetAllGPSLive), ctx)
}

// GetGPSHistory mocks base method.
func (m *MockVehicle) GetGPSHistory(ctx context.Context, vehicleIDOrTarga string, limit int) ([]dto.GPSHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGPSHistory", ctx, vehicleIDOrTarga, limit)
	ret0, _ := ret[0].([]dto.GPSHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGPSHistory indicates an expected call of GetGPSHistory.
func (mr *MockVehicleMockRecorder) GetGPSHistory(ctx, vehicleIDOrTarga, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGPSHistory", reflect.TypeOf((*MockVehicle)(nil).GetGPSHistory), ctx, vehicleIDOrTarga, limit)
}

// GetTemperatureHistory mocks base method.
func (m *MockVehicle) GetTemperatureHistory(ctx context.Context, vehicleID uuid.UUID, limit int, onlyAlerts bool) ([]dto.TemperatureReadingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemperatureHistory", ctx, vehicleID, limit, onlyAlerts)
	ret0, _ := ret[0].([]dto.TemperatureReadingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemperatureHistory indicates an expected call of GetTemperatureHistory.
func (mr *MockVehicleMockRecorder) GetTemperatureHistory(ctx, vehicleID, limit, onlyAlerts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemperatureHistory", reflect.TypeOf((*MockVehicle)(nil).GetTemperatureHistory), ctx, vehicleID, limit, onlyAlerts)
}

// IngestGPSWebhook mocks base method.
func (m *MockVehicle) IngestGPSWebhook(ctx context.Context, vendor string, payload dto.GPSWebhookPayload) (*dto.GPSUpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestGPSWebhook", ctx, vendor, payload)
	ret0, _ := ret[0].(*dto.GPSUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestGPSWebhook indicates an expected call of IngestGPSWebhook.
func (mr *MockVehicleMockRecorder) IngestGPSWebhook(ctx, vendor, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestGPSWebhook", reflect.TypeOf((*MockVehicle)(nil).IngestGPSWebhook), ctx, vendor, payload)
}

// IngestTemperatureWebhook mocks base method.
func (m *MockVehicle) IngestTemperatureWebhook(ctx context.Context, vendor string, payload dto.TemperatureWebhookRequest) (*dto.TemperatureWebhookResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IngestTemperatureWebhook", ctx, vendor, payload)
	ret0, _ := ret[0].(*dto.TemperatureWebhookResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IngestTemperatureWebhook indicates an expected call of IngestTemperatureWebhook.
func (mr *MockVehicleMockRecorder) IngestTemperatureWebhook(ctx, vendor, payload interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IngestTemperatureWebhook", reflect.TypeOf((*MockVehicle)(nil).IngestTemperatureWebhook), ctx, vendor, payload)
}

// List mocks base method.
func (m *MockVehicle) List(ctx context.Context, search string) ([]dto.VehicleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, search)
	ret0, _ := ret[0].([]dto.VehicleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVehicleMockRecorder) List(ctx, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVehicle)(nil).List), ctx, search)
}

// SetTemperatureThresholds mocks base method.
func (m *MockVehicle) SetTemperatureThresholds(ctx context.Context, vehicleID uuid.UUID, req dto.TemperatureThresholdsRequest) (*dto.TemperatureThresholdsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTemperatureThresholds", ctx, vehicleID, req)
	ret0, _ := ret[0].(*dto.TemperatureThresholdsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetTemperatureThresholds indicates an expected call of SetTemperatureThresholds.
func (mr *MockVehicleMockRecorder) SetTemperatureThresholds(ctx, vehicleID, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTemperatureThresholds", reflect.TypeOf((*MockVehicle)(nil).SetTemperatureThresholds), ctx, vehicleID, req)
}

// Update mocks base method.
func (m *MockVehicle) Update(ctx context.Context, id uuid.UUID, req dto.VehicleRequest) (*dto.VehicleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.VehicleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVehicleMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVehicle)(nil).Update), ctx, id, req)
}

// UpdateGPSByID mocks base method.
func (m *MockVehicle) UpdateGPSByID(ctx context.Context, idOrTarga string, req dto.VehicleGPSUpdateRequest) (*dto.GPSUpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGPSByID", ctx, idOrTarga, req)
	ret0, _ := ret[0].(*dto.GPSUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGPSByID indicates an expected call of UpdateGPSByID.
func (mr *MockVehicleMockRecorder) UpdateGPSByID(ctx, idOrTarga, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGPSByID", reflect.TypeOf((*MockVehicle)(nil).UpdateGPSByID), ctx, idOrTarga, req)
}

// UpdateGPSByPlate mocks base method.
func (m *MockVehicle) UpdateGPSByPlate(ctx context.Context, targa string, req dto.VehicleGPSUpdateRequest) (*dto.GPSUpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGPSByPlate", ctx, targa, req)
	ret0, _ := ret[0].(*dto.GPSUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGPSByPlate indicates an expected call of UpdateGPSByPlate.
func (mr *MockVehicleMockRecorder) UpdateGPSByPlate(ctx, targa, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGPSByPlate", reflect.TypeOf((*MockVehicle)(nil).UpdateGPSByPlate), ctx, targa, req)
}

// MockTrip is a mock of Trip interface.
type MockTrip struct {
	ctrl     *gomock.Controller
	recorder *MockTripMockRecorder
}

// MockTripMockRecorder is the mock recorder for MockTrip.
type MockTripMockRecorder struct {
	mock *MockTrip
}

// NewMockTrip creates a new mock instance.
func NewMockTrip(ctrl *gomock.Controller) *MockTrip {
	mock := &MockTrip{ctrl: ctrl}
	mock.recorder = &MockTripMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrip) EXPECT() *MockTripMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockTrip) AddOrder(ctx context.Context, tripID, orderID uuid.UUID) (*dto.OKResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", ctx, tripID, orderID)
	ret0, _ := ret[0].(*dto.OKResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockTripMockRecorder) AddOrder(ctx, tripID, orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockTrip)(nil).AddOrder), ctx, tripID, orderID)
}

// Complete mocks base method.
func (m *MockTrip) Complete(ctx context.Context, id uuid.UUID) (*dto.OKResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, id)
	ret0, _ := ret[0].(*dto.OKResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockTripMockRecorder) Complete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockTrip)(nil).Complete), ctx, id)
}

// Create mocks base method.
func (m *MockTrip) Create(ctx context.Context, req dto.TripRequest) (*dto.TripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.TripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTripMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTrip)(nil).Create), ctx, req)
}

// GetByID mocks base method.
func (m *MockTrip) GetByID(ctx context.Context, id uuid.UUID) (*dto.TripDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.TripDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTripMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTrip)(nil).GetByID), ctx, id)
}

// GetInstructionsPDF mocks base method.
func (m *MockTrip) GetInstructionsPDF(ctx context.Context, id uuid.UUID) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInstructionsPDF", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetInstructionsPDF indicates an expected call of GetInstructionsPDF.
func (mr *MockTripMockRecorder) GetInstructionsPDF(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstructionsPDF", reflect.TypeOf((*MockTrip)(nil).GetInstructionsPDF), ctx, id)
}

// List mocks base method.
func (m *MockTrip) List(ctx context.Context, stato string, limit int) ([]dto.TripResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, stato, limit)
	ret0, _ := ret[0].([]dto.TripResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTripMockRecorder) List(ctx, stato, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTrip)(nil).List), ctx, stato, limit)
}

// RecomputeSegments mocks base method.
func (m *MockTrip) RecomputeSegments(ctx context.Context, id uuid.UUID) (*dto.RecomputeSegmentsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecomputeSegments", ctx, id)
	ret0, _ := ret[0].(*dto.RecomputeSegmentsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecomputeSegments indicates an expected call of RecomputeSegments.
func (mr *MockTripMockRecorder) RecomputeSegments(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecomputeSegments", reflect.TypeOf((*MockTrip)(nil).RecomputeSegments), ctx, id)
}

// Start mocks base method.
func (m *MockTrip) Start(ctx context.Context, id uuid.UUID) (*dto.OKResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, id)
	ret0, _ := ret[0].(*dto.OKResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockTripMockRecorder) Start(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTrip)(nil).Start), ctx, id)
}

// MockPriceList is a mock of PriceList interface.
type MockPriceList struct {
	ctrl     *gomock.Controller
	recorder *MockPriceListMockRecorder
}

// MockPriceListMockRecorder is the mock recorder for MockPriceList.
type MockPriceListMockRecorder struct {
	mock *MockPriceList
}

// NewMockPriceList creates a new mock instance.
func NewMockPriceList(ctrl *gomock.Controller) *MockPriceList {
	mock := &MockPriceList{ctrl: ctrl}
	mock.recorder = &MockPriceListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceList) EXPECT() *MockPriceListMockRecorder {
	return m.recorder
}

// AddItem mocks base method.
func (m *MockPriceList) AddItem(ctx context.Context, plID uuid.UUID, item dto.PriceListItemRequestDTO) (*dto.PriceListItemAddResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItem", ctx, plID, item)
	ret0, _ := ret[0].(*dto.PriceListItemAddResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItem indicates an expected call of AddItem.
func (mr *MockPriceListMockRecorder) AddItem(ctx, plID, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItem", reflect.TypeOf((*MockPriceList)(nil).AddItem), ctx, plID, item)
}

// Create mocks base method.
func (m *MockPriceList) Create(ctx context.Context, req dto.PriceListRequest) (*dto.PriceListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.PriceListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPriceListMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPriceList)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockPriceList) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPriceListMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPriceList)(nil).Delete), ctx, id)
}

// DeleteItem mocks base method.
func (m *MockPriceList) DeleteItem(ctx context.Context, plID, itemID uuid.UUID) (*dto.PriceListItemDeleteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, plID, itemID)
	ret0, _ := ret[0].(*dto.PriceListItemDeleteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockPriceListMockRecorder) DeleteItem(ctx, plID, itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockPriceList)(nil).DeleteItem), ctx, plID, itemID)
}

// GetByID mocks base method.
func (m *MockPriceList) GetByID(ctx context.Context, id uuid.UUID) (*dto.PriceListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.PriceListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPriceListMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPriceList)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockPriceList) List(ctx context.Context, clienteID string) ([]dto.PriceListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, clienteID)
	ret0, _ := ret[0].([]dto.PriceListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPriceListMockRecorder) List(ctx, clienteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPriceList)(nil).List), ctx, clienteID)
}

// LookupTariff mocks base method.
func (m *MockPriceList) LookupTariff(ctx context.Context, clienteID, caricoID, scaricoID, prodottoID string, peso float64) (*dto.TariffLookupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LookupTariff", ctx, clienteID, caricoID, scaricoID, prodottoID, peso)
	ret0, _ := ret[0].(*dto.TariffLookupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LookupTariff indicates an expected call of LookupTariff.
func (mr *MockPriceListMockRecorder) LookupTariff(ctx, clienteID, caricoID, scaricoID, prodottoID, peso interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LookupTariff", reflect.TypeOf((*MockPriceList)(nil).LookupTariff), ctx, clienteID, caricoID, scaricoID, prodottoID, peso)
}

// Update mocks base method.
func (m *MockPriceList) Update(ctx context.Context, id uuid.UUID, req dto.PriceListRequest) (*dto.PriceListUpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.PriceListUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPriceListMockRecorder) Update(ctx, id, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPriceList)(nil).Update), ctx, id, req)
}

// UpdateItem mocks base method.
func (m *MockPriceList) UpdateItem(ctx context.Context, plID, itemID uuid.UUID, item dto.PriceListItemRequestDTO) (*dto.PriceListItemUpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, plID, itemID, item)
	ret0, _ := ret[0].(*dto.PriceListItemUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockPriceListMockRecorder) UpdateItem(ctx, plID, itemID, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockPriceList)(nil).UpdateItem), ctx, plID, itemID, item)
}

// MockInvoice is a mock of Invoice interface.
type MockInvoice struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceMockRecorder
}

// MockInvoiceMockRecorder is the mock recorder for MockInvoice.
type MockInvoiceMockRecorder struct {
	mock *MockInvoice
}

// NewMockInvoice creates a new mock instance.
func NewMockInvoice(ctrl *gomock.Controller) *MockInvoice {
	mock := &MockInvoice{ctrl: ctrl}
	mock.recorder = &MockInvoiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoice) EXPECT() *MockInvoiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockInvoice) Create(ctx context.Context, req dto.InvoiceRequest) (*dto.InvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.InvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockInvoiceMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockInvoice)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockInvoice) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockInvoiceMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockInvoice)(nil).Delete), ctx, id)
}

// Finalize mocks base method.
func (m *MockInvoice) Finalize(ctx context.Context, id uuid.UUID) (*dto.InvoiceFinalizeResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Finalize", ctx, id)
	ret0, _ := ret[0].(*dto.InvoiceFinalizeResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Finalize indicates an expected call of Finalize.
func (mr *MockInvoiceMockRecorder) Finalize(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finalize", reflect.TypeOf((*MockInvoice)(nil).Finalize), ctx, id)
}

// GetByID mocks base method.
func (m *MockInvoice) GetByID(ctx context.Context, id uuid.UUID) (*dto.InvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.InvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockInvoiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockInvoice)(nil).GetByID), ctx, id)
}

// GetPDF mocks base method.
func (m *MockInvoice) GetPDF(ctx context.Context, id uuid.UUID) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPDF", ctx, id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetPDF indicates an expected call of GetPDF.
func (mr *MockInvoiceMockRecorder) GetPDF(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPDF", reflect.TypeOf((*MockInvoice)(nil).GetPDF), ctx, id)
}

// GetPDFPresignedURL mocks base method.
func (m *MockInvoice) GetPDFPresignedURL(ctx context.Context, id uuid.UUID) (*dto.InvoicePDFURLResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPDFPresignedURL", ctx, id)
	ret0, _ := ret[0].(*dto.InvoicePDFURLResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPDFPresignedURL indicates an expected call of GetPDFPresignedURL.
func (mr *MockInvoiceMockRecorder) GetPDFPresignedURL(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPDFPresignedURL", reflect.TypeOf((*MockInvoice)(nil).GetPDFPresignedURL), ctx, id)
}

// List mocks base method.
func (m *MockInvoice) List(ctx context.Context, stato, clienteID string) ([]dto.InvoiceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, stato, clienteID)
	ret0, _ := ret[0].([]dto.InvoiceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockInvoiceMockRecorder) List(ctx, stato, clienteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockInvoice)(nil).List), ctx, stato, clienteID)
}

// MockDashboard is a mock of Dashboard interface.
type MockDashboard struct {
	ctrl     *gomock.Controller
	recorder *MockDashboardMockRecorder
}

// MockDashboardMockRecorder is the mock recorder for MockDashboard.
type MockDashboardMockRecorder struct {
	mock *MockDashboard
}

// NewMockDashboard creates a new mock instance.
func NewMockDashboard(ctrl *gomock.Controller) *MockDashboard {
	mock := &MockDashboard{ctrl: ctrl}
	mock.recorder = &MockDashboardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDashboard) EXPECT() *MockDashboardMockRecorder {
	return m.recorder
}

// CustomerDashboard mocks base method.
func (m *MockDashboard) CustomerDashboard(ctx context.Context, customerID uuid.UUID) (*dto.CustomerDashboardResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomerDashboard", ctx, customerID)
	ret0, _ := ret[0].(*dto.CustomerDashboardResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomerDashboard indicates an expected call of CustomerDashboard.
func (mr *MockDashboardMockRecorder) CustomerDashboard(ctx, customerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomerDashboard", reflect.TypeOf((*MockDashboard)(nil).CustomerDashboard), ctx, customerID)
}

// RecentOrders mocks base method.
func (m *MockDashboard) RecentOrders(ctx context.Context) ([]dto.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentOrders", ctx)
	ret0, _ := ret[0].([]dto.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentOrders indicates an expected call of RecentOrders.
func (mr *MockDashboardMockRecorder) RecentOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentOrders", reflect.TypeOf((*MockDashboard)(nil).RecentOrders), ctx)
}

// Stats mocks base method.
func (m *MockDashboard) Stats(ctx context.Context) (*dto.DashboardStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx)
	ret0, _ := ret[0].(*dto.DashboardStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockDashboardMockRecorder) Stats(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockDashboard)(nil).Stats), ctx)
}

// MockMap is a mock of Map interface.
type MockMap struct {
	ctrl     *gomock.Controller
	recorder *MockMapMockRecorder
}

// MockMapMockRecorder is the mock recorder for MockMap.
type MockMapMockRecorder struct {
	mock *MockMap
}

// NewMockMap creates a new mock instance.
func NewMockMap(ctrl *gomock.Controller) *MockMap {
	mock := &MockMap{ctrl: ctrl}
	mock.recorder = &MockMapMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMap) EXPECT() *MockMapMockRecorder {
	return m.recorder
}

// Trips mocks base method.
func (m *MockMap) Trips(ctx context.Context) (*dto.MapTripsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trips", ctx)
	ret0, _ := ret[0].(*dto.MapTripsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Trips indicates an expected call of Trips.
func (mr *MockMapMockRecorder) Trips(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trips", reflect.TypeOf((*MockMap)(nil).Trips), ctx)
}

// MockGeocode is a mock of Geocode interface.
type MockGeocode struct {
	ctrl     *gomock.Controller
	recorder *MockGeocodeMockRecorder
}

// MockGeocodeMockRecorder is the mock recorder for MockGeocode.
type MockGeocodeMockRecorder struct {
	mock *MockGeocode
}

// NewMockGeocode creates a new mock instance.
func NewMockGeocode(ctrl *gomock.Controller) *MockGeocode {
	mock := &MockGeocode{ctrl: ctrl}
	mock.recorder = &MockGeocodeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGeocode) EXPECT() *MockGeocodeMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockGeocode) Search(ctx context.Context, query string) ([]dto.GeocodeResultDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query)
	ret0, _ := ret[0].([]dto.GeocodeResultDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockGeocodeMockRecorder) Search(ctx, query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockGeocode)(nil).Search), ctx, query)
}

// MockAvailability is a mock of Availability interface.
type MockAvailability struct {
	ctrl     *gomock.Controller
	recorder *MockAvailabilityMockRecorder
}

// MockAvailabilityMockRecorder is the mock recorder for MockAvailability.
type MockAvailabilityMockRecorder struct {
	mock *MockAvailability
}

// NewMockAvailability creates a new mock instance.
func NewMockAvailability(ctrl *gomock.Controller) *MockAvailability {
	mock := &MockAvailability{ctrl: ctrl}
	mock.recorder = &MockAvailabilityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvailability) EXPECT() *MockAvailabilityMockRecorder {
	return m.recorder
}

// DriverAvailability mocks base method.
func (m *MockAvailability) DriverAvailability(ctx context.Context, dataDa, dataA string) ([]dto.DriverAvailabilityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DriverAvailability", ctx, dataDa, dataA)
	ret0, _ := ret[0].([]dto.DriverAvailabilityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DriverAvailability indicates an expected call of DriverAvailability.
func (mr *MockAvailabilityMockRecorder) DriverAvailability(ctx, dataDa, dataA interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DriverAvailability", reflect.TypeOf((*MockAvailability)(nil).DriverAvailability), ctx, dataDa, dataA)
}

// VehicleAvailability mocks base method.
func (m *MockAvailability) VehicleAvailability(ctx context.Context, dataDa, dataA string) ([]dto.VehicleAvailabilityResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VehicleAvailability", ctx, dataDa, dataA)
	ret0, _ := ret[0].([]dto.VehicleAvailabilityResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VehicleAvailability indicates an expected call of VehicleAvailability.
func (mr *MockAvailabilityMockRecorder) VehicleAvailability(ctx, dataDa, dataA interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VehicleAvailability", reflect.TypeOf((*MockAvailability)(nil).VehicleAvailability), ctx, dataDa, dataA)
}

// MockExport is a mock of Export interface.
type MockExport struct {
	ctrl     *gomock.Controller
	recorder *MockExportMockRecorder
}

// MockExportMockRecorder is the mock recorder for MockExport.
type MockExportMockRecorder struct {
	mock *MockExport
}

// NewMockExport creates a new mock instance.
func NewMockExport(ctrl *gomock.Controller) *MockExport {
	mock := &MockExport{ctrl: ctrl}
	mock.recorder = &MockExportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExport) EXPECT() *MockExportMockRecorder {
	return m.recorder
}

// OrdersExcel mocks base method.
func (m *MockExport) OrdersExcel(ctx context.Context, filter export.OrdersFilter) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrdersExcel", ctx, filter)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrdersExcel indicates an expected call of OrdersExcel.
func (mr *MockExportMockRecorder) OrdersExcel(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrdersExcel", reflect.TypeOf((*MockExport)(nil).OrdersExcel), ctx, filter)
}
